language: go
dist: bionic

go:
- 1.12.x

env:
  global:
    - PODMAN_VERSION=1.6.0-rc1

addons:
  apt:
    packages:
    - btrfs-tools
    - git
    - go-md2man
    - iptables
    - libassuan-dev
    - libc6-dev
    - libdevmapper-dev
    - libglib2.0-dev
    - libgpgme-dev
    - libgpg-error-dev
    - libostree-dev
    - libprotobuf-dev
    - libprotobuf-c0-dev
    - libseccomp-dev
    - libselinux1-dev
    - libsystemd-dev
    - pkg-config
    - runc
    - uidmap

script:
  - git clone -q --branch=v$PODMAN_VERSION --single-branch https://github.com/containers/libpod/ $GOPATH/src/github.com/containers/libpod
  - cd $GOPATH/src/github.com/containers/libpod
  - make podman-remote-windows-release
  - ls -lah bin

before_deploy:
  - git tag $PODMAN_VERSION

deploy:
  skip_cleanup: true
  provider: releases
  api_key: $GITHUB_TOKEN
  file: bin/podman-remote-windows.exe
  on:
    branch: master
